### ISSUE TITLE
Dev mode ignores dotfiles

### ISSUE THREAD

**Issue by sonicdoe** [lukeed/sirv#51]
If [`dev`](https://github.com/lukeed/sirv/tree/master/packages/sirv#optsdev) mode is enabled, [`dotfiles`](https://github.com/lukeed/sirv/tree/master/packages/sirv#optsdotfiles) is ignored.

For example, a file named `.foo.txt` is served in `dev` mode even if `dotfiles` is set to `false`.

**Comment by lukeed** [comment]
Thanks for the report – this is fixed in `next` which will be promoted to 1.0 asap.

**Comment by sonicdoe** [comment]
I can still reproduce this with sirv v1.0.0. If I set `dev` to `true` and `dotfiles` to `false`, sirv serves a file named `.foo.txt`.

**Comment by sonicdoe** [comment]
@lukeed Thank you for adding some tests with https://github.com/lukeed/sirv/commit/d01fe7260e7099eb4c723d152b1ace44075927a4. However, the assertions in “[should reject hidden files by default (dev: true)](https://github.com/lukeed/sirv/blob/45e2dafabb65fc68b7fb3ec21d47bf40a2cbb8d4/tests/sirv.js#L492-L510)” aren’t executed because the catch block is never called. In fact, the status code is 200 OK for all three responses.
